remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
- jekyll-include-cache
- jekyll-sitemap

include: ["_pages"]

logo: "/assets/images/crested-wm-full-colour.png"
title: BUI

atom_feed:
  hide: true
  